#!/bin/sh
if [ "x$CHECK_AS400_CP" == "x" ]; then
    CHECK_AS400_CP=$(dirname $(readlink -f $0))
fi

if [ "x$CHECK_AS400_CREDENTIAL_FILE" == "x" ]; then
    CHECK_AS400_CREDENTIAL_FILE=".as400"
fi

CHECK_AS400_CREDENTIAL_PARAMS=""
if [ -e $CHECK_AS400_CREDENTIAL_FILE ]; then
    USR=`grep USER $CHECK_AS400_CREDENTIAL_FILE | cut -d = -f 2`
    PASS=`grep PASS $CHECK_AS400_CREDENTIAL_FILE | cut -d = -f 2`
    CHECK_AS400_CREDENTIAL_PARAMS="-u $USR -p $PASS"
fi

java -cp $CHECK_AS400_CP check_as400 $CHECK_AS400_CREDENTIAL_PARAMS $*
